<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1681450472448' stop='1681450540204'>
    <name>Issue actions test: change issue</name>
    <title>Issue actions test: change issue</title>
    <test-cases>
        <test-case start='1681450472449' status='broken' stop='1681450540198'>
            <name>issue should be blocked</name>
            <title>issue should be blocked</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-111.0.5563.111'/>
                <parameter kind='argument' name='browser' value='chrome-111.0.5563.111'/>
                <parameter kind='argument' name='browser' value='chrome-111.0.5563.111'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "change issue issue should be blocked" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\lebra\Documents\GitHub\autotest-ips\src\issues\test\issues.test.ts)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "change issue issue should be blocked" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\lebra\Documents\GitHub\autotest-ips\src\issues\test\issues.test.ts)
                    at createTimeoutError (C:\Users\lebra\Documents\GitHub\autotest-ips\node_modules\mocha\lib\errors.js:498:15)
                    at Test.Runnable._timeoutError (C:\Users\lebra\Documents\GitHub\autotest-ips\node_modules\mocha\lib\runnable.js:431:10)
                    at Timeout.&lt;anonymous> (C:\Users\lebra\Documents\GitHub\autotest-ips\node_modules\mocha\lib\runnable.js:246:24)
                    at listOnTimeout (internal/timers.js:557:17)
                    at processTimers (internal/timers.js:500:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>